### ISSUE TITLE
Unresolved imports

### ISSUE THREAD

**Issue by ghost** [mitsuhiko/self-replace#17]
error[E0432]: unresolved import `windows_sys::Win32::Security`
  --> C:\Users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\self-replace-1.3.5\src\windows.rs:16:25
   |
16 | use windows_sys::Win32::Security::SECURITY_ATTRIBUTES;
   |                         ^^^^^^^^ could not find `Security` in `Win32`

error[E0432]: unresolved import `windows_sys::Win32::Storage::FileSystem::CreateFileW`
  --> C:\Users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\self-replace-1.3.5\src\windows.rs:18:5
   |
18 |     CreateFileW, DeleteFileW, FILE_FLAG_DELETE_ON_CLOSE, FILE_SHARE_DELETE, FILE_SHARE_READ,
   |     ^^^^^^^^^^^ no `CreateFileW` in `Windows::Win32::Storage::FileSystem`

error[E0432]: unresolved import `windows_sys::Win32::System::Threading::CreateProcessA`
  --> C:\Users\foo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\self-replace-1.3.5\src\windows.rs:25:5
   |
25 |     CreateProcessA, ExitProcess, GetCurrentProcess, WaitForSingleObject, CREATE_NO_WINDOW,
   |     ^^^^^^^^^^^^^^ no `CreateProcessA` in `Windows::Win32::System::Threading`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `self-replace` (lib) due to 3 previous errors

**Comment by 13-05** [comment]
Same issue when cross-compiling to target `x86_64-pc-windows-msvc` using [cargo-xwin](https://github.com/rust-cross/cargo-xwin). @mitsuhiko do you have any ideas?

**Comment by exalented** [comment]
Why isn't this merged?

**Comment by mitsuhiko** [comment]
This is resolved.
