### ISSUE TITLE
How to use self-replace crate for updating a Rust app when a new version is available?

### ISSUE THREAD

**Issue by Gio2241** [mitsuhiko/self-replace#3]
Dear crate authors of self-replace,

I am working on a Rust application where I would like to use the self-replace crate to update the running app when a new version is available, which I will check using an `is_update_available` method. Additionally, my app has running threads which process user requests, so I need some mechanism to wait for these threads to finish their tasks and not receive any more requests before applying the update. I am looking for guidance on how to properly implement this functionality and integrate it with your crate.

I have found some examples in the documentation, but I am not sure how to adapt them to my specific use case.

Here's an outline of what I want to achieve:

* Periodically check for updates using the is_update_available method.
* If an update is available, wait for the running threads to finish their tasks and not receive any more requests (`Axum` server)
* Download and apply the update using the `self-replace` crate.
* Restart the application with the new version.

Could you please provide some guidance or examples on how to accomplish these tasks using your crate, especially in the context of gracefully handling running threads? Any help would be greatly appreciated.

Thank you in advance, Alex

**Comment by kochia7** [comment]
I'm on Ubuntu Server.
Thanks Armin for the details, I was not aware of  `SO_REUSEPORT`
